version: '3'
services:
  windows:
    image: dockur/windows
    container_name: windows_container
    environment:
      VERSION: "11l"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
      # 👇 Yeh dono lines aap ke bataye huwe credentials auto-configure kar dengi
      USERNAME: "Haiderrdp"
      PASSWORD: "Haiderrdp"
    ports:
      - "8006:8006"
      - "3389:3389" # RDP port mapping
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    restart: on-failure
