services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://iso.biglinux.com.br/biglinux_2026-04-18_k618.iso"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
      USERNAME: "bill"
      PASSWORD: "gates"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
